#include<bits/stdc++.h>
using namespace std;
int main()
{
    int t,n,i,j,ca,cb,cc,s1;
    cin>>t;
    while(t--)
    {
        string s;
        cin>>s;
        n=s.size();
        ca=1,s1=0;
        for(i=0; i<n; i++)
        {
            if(s[i]=='A')
            {
                s1++;
            }
            else
            {
                s1--;
            }
            if(s1<0)
            {
                ca=0;
                break;
            }
        }
        if(s1!=0)
        {
            ca=0;
        }
        cb=1,s1=0;
        for(i=0; i<n; i++)
        {
            if(s[i]=='B')
            {
                s1++;
            }
            else
            {
                s1--;
            }
            if(s1<0)
            {
                cb=0;
                break;
            }
        }
        if(s1!=0)
        {
            cb=0;
        }
        cc=1,s1=0;
        for(i=0; i<n; i++)
        {
            if(s[i]=='C')
            {
                s1++;
            }
            else
            {
                s1--;
            }
            if(s1<0)
            {
                cc=0;
                break;
            }
        }
        if(s1!=0)
        {
            cc=0;
        }
        if(ca||cb||cc)
        {
            cout<<"YES"<<endl;
        }
        else
        {
            ca=1,s1=0;
        for(i=0; i<n; i++)
        {
            if(s[i]=='A'||s[i]=='B')
            {
                s1++;
            }
            else
            {
                s1--;
            }
            if(s1<0)
            {
                ca=0;
                break;
            }
        }
        if(s1!=0)
        {
            ca=0;
        }
        cb=1,s1=0;
        for(i=0; i<n; i++)
        {
            if(s[i]=='B'||s[i]=='C')
            {
                s1++;
            }
            else
            {
                s1--;
            }
            if(s1<0)
            {
                cb=0;
                break;
            }
        }
        if(s1!=0)
        {
            cb=0;
        }
        cc=1,s1=0;
        for(i=0; i<n; i++)
        {
            if(s[i]=='C'||s[i]=='A')
            {
                s1++;
            }
            else
            {
                s1--;
            }
            if(s1<0)
            {
                cc=0;
                break;
            }
        }
        if(s1!=0)
        {
            cc=0;
        }
            if(ca||cb||cc)
        {
            cout<<"YES"<<endl;
        }
        else
        {
            cout<<"NO"<<endl;
        }
        }
    }
    return 0;
}
