#include<bits/stdc++.h>
using namespace std;
typedef long long ll;
int main()
{
    ll t,n,m,i,j,c1,c2;
    char s[55][55];
    char ch,ch1;
    cin>>t;
    while(t--)
    {
        cin>>n>>m;
        for(i=0;i<n;i++)
        {
            for(j=0;j<m;j++)
            {
                cin>>s[i][j];
            }
        }
        c1=0;
        ch='W';
        for(i=0;i<n;i++)
        {
            if(ch=='W')
            {
                ch='R';
            }
            else
            {
                ch='W';
            }
            ch1=ch;
            for(j=0;j<m;j++)
            {
                if(ch1=='R'&&s[i][j]=='W')
                {
                    c1=1;
                    break;
                }
                else if(ch1=='W'&&s[i][j]=='R')
                {
                    c1=1;
                    break;
                }
                else
                {
                    if(ch1=='W')
            {
                ch1='R';
            }
            else
            {
                ch1='W';
            }
                }
            }
        }
        if(c1==0)
        {
            cout<<"YES"<<endl;
            ch='W';
            for(i=0;i<n;i++)
        {
             if(ch=='W')
            {
                ch='R';
            }
            else
            {
                ch='W';
            }
            ch1=ch;
            for(j=0;j<m;j++)
            {
                cout<<ch1;
                if(ch1=='W')
            {
                ch1='R';
            }
            else
            {
                ch1='W';
            }
            }
            cout<<endl;
        }
        cout<<endl;
        }
        else
        {
            c1=0;
        ch='R';
             for(i=0;i<n;i++)
        {
            if(ch=='W')
            {
                ch='R';
            }
            else
            {
                ch='W';
            }
            ch1=ch;
            for(j=0;j<m;j++)
            {
                if(ch1=='R'&&s[i][j]=='W')
                {
                    c1=1;
                    break;
                }
                else if(ch1=='W'&&s[i][j]=='R')
                {
                    c1=1;
                    break;
                }
                else
                {
                    if(ch1=='W')
            {
                ch1='R';
            }
            else
            {
                ch1='W';
            }
                }
            }
        }
        if(c1==1)
        {
            cout<<"NO"<<endl;
        }
        else
        {
            cout<<"YES"<<endl;
            ch='R';
            for(i=0;i<n;i++)
        {
             if(ch=='W')
            {
                ch='R';
            }
            else
            {
                ch='W';
            }
            ch1=ch;
            for(j=0;j<m;j++)
            {
                cout<<ch1;
                if(ch1=='W')
            {
                ch1='R';
            }
            else
            {
                ch1='W';
            }
            }
            cout<<endl;
        }
        cout<<endl;
        }
        }

    }
    return 0;
}
